### PR TITLE
recursively parse content of nodes inside prop

### PR DESCRIPTION
**Pull request by georgehrke**
before:
developer_tools_-_http_--owncloud_dev-index_php-apps-calendar-_chromium__today_at_2_17_52_pm

after:
new

@evert @DeepDiver1975 @PVince81 @Henni

### CODE REVIEW

**Comment by georgehrke** [comment]
Also the namespaces in very nested objects like acl are properly resolved:
developer tools - http --owncloud dev-index php-apps-calendar- chromium today at 10 29 38 pm

**Comment by PVince81** [comment]
@georgehrke have you tested this in IE ? (at least IE 11 / Edge) and maybe Safari

**Comment by georgehrke** [comment]
not yet

**Comment by PVince81** [comment]
I tested this change in OC and it breaks the folder detection in the file list, probably because it expects the old format. Once you do a PR in OC to upgrade the lib, please also include a fix for the files client. :smile:

**Comment by evert** [comment]
Looks good to me. Ready for a merge?

**Comment by PVince81** [comment]
Sounds good :+1:

**Comment by georgehrke** [comment]
I've been thinking a lot about this and digging into the MDN pages about Elements.

This pr brings only very little benefit (actually a lot less than I initially figured it would) while also breaking most of our the existing code. 😕 
I'd actually like to propose reverting it.

What do you think about this? @PVince81 @evert

**Comment by PVince81** [comment]
@georgehrke can you elaborate ?

I don't mind reverting.

**Comment by evert** [comment]
I trust @PVince81

**Comment by georgehrke** [comment]
This way we remove all the awesome helper properties and methods in [Node objects](https://developer.mozilla.org/en-US/docs/Web/API/Node).
Since the response is XML it's perfectly reasonable to hand raw Node objects over to the developer.

**Comment by PVince81** [comment]
Revert PR here https://github.com/evert/davclient.js/pull/21

**Pull request merged**
