### PR TITLE
Added basic tests

### PR DESCRIPTION
**Pull request by PVince81**
Basic test for "requests" method.

More to come in the future when I have more time.

@evert please review

### CODE REVIEW

**Comment by PVince81** [comment]
I'll see if I can make Travis actually test this...

**Comment by PVince81** [comment]
Seems I can't as it's your repo.

@evert can you enable travis testing ? It should be in your profile page on Travis.
Thanks.

**Comment by PVince81** [comment]
More tests added.

**Comment by PVince81** [comment]
Even more tests added.

The function `resolveUrl` seems a bit suspicious and non-working. I wasn't able to fix it.

If the other tests are acceptable, I'd like to merge them first and disable the broken cases to be fixed separately.

**Comment by evert** [comment]
This is awesome!

**Comment by evert** [comment]
Got some build failures now, but travis ci integration works

**Comment by PVince81** [comment]
Thanks for merging, will take care of it. I have a solution that worked on my fork, will send it over as PR.On Mar 8, 2017 1:39 AM, Evert Pot <notifications@github.com> wrote:Got some build failures now, but travis ci integration works

**Pull request merged**
