### PR TITLE
Add onProgress callback

### PR DESCRIPTION
**Pull request by PVince81**

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
Travis needs love ....

**Comment by PVince81** [comment]
currently still draft. I want to test this with the code that actually uses this.

then I'll move forward to make this mergable

**Comment by PVince81** [comment]
@DeepDiver1975 Travis fix here: https://github.com/owncloud/davclient.js/pull/40

**Comment by PVince81** [comment]
rebased for Travis fixes

**Comment by PVince81** [comment]
Fixed. I mistakenly used ES6 syntax.

**Pull request merged**
